### ISSUE TITLE
Proposal to use provider from including module instead of instantiating within the module

### ISSUE THREAD

**Issue by jcsmith** [vmware/terraform-vsphere-avi-alb-deployment-vsphere#1]
### Is your feature request related to a problem? Please describe.

When using this module as part of another module that also uses the vsphere provider it is a bit unwieldy to also have the provider instantiate its own instance of the vsphere provider.  I'd like to propose the removal of the provider block within this module and instead rely on terraform's ability to inherit providers from the parent module (https://www.terraform.io/language/modules/develop/providers)

### Describe the solution you'd like

Removal of the :
```
provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  allow_unverified_ssl = true
}
```
black as well as associated input variables from the module and instead rely on provider inheritance. 

### Additional context

More than happy to submit a PR making these changes if you are interested.

**Comment by slarimore02** [comment]
@jcsmith the provider block has been removed from within the module. Thank you for your proposal and if there's anything else you'd like to see improved please let me know.
